// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: pb/messages.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	FetchTopStories(ctx context.Context, in *TopCountRequest, opts ...grpc.CallOption) (*TopCountResponse, error)
	FetchItems(ctx context.Context, in *TopCountResponse, opts ...grpc.CallOption) (*ResponseStories, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) FetchTopStories(ctx context.Context, in *TopCountRequest, opts ...grpc.CallOption) (*TopCountResponse, error) {
	out := new(TopCountResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/FetchTopStories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) FetchItems(ctx context.Context, in *TopCountResponse, opts ...grpc.CallOption) (*ResponseStories, error) {
	out := new(ResponseStories)
	err := c.cc.Invoke(ctx, "/EmployeeService/FetchItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
// All implementations must embed UnimplementedEmployeeServiceServer
// for forward compatibility
type EmployeeServiceServer interface {
	FetchTopStories(context.Context, *TopCountRequest) (*TopCountResponse, error)
	FetchItems(context.Context, *TopCountResponse) (*ResponseStories, error)
	mustEmbedUnimplementedEmployeeServiceServer()
}

// UnimplementedEmployeeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (UnimplementedEmployeeServiceServer) FetchTopStories(context.Context, *TopCountRequest) (*TopCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTopStories not implemented")
}
func (UnimplementedEmployeeServiceServer) FetchItems(context.Context, *TopCountResponse) (*ResponseStories, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchItems not implemented")
}
func (UnimplementedEmployeeServiceServer) mustEmbedUnimplementedEmployeeServiceServer() {}

// UnsafeEmployeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServiceServer will
// result in compilation errors.
type UnsafeEmployeeServiceServer interface {
	mustEmbedUnimplementedEmployeeServiceServer()
}

func RegisterEmployeeServiceServer(s grpc.ServiceRegistrar, srv EmployeeServiceServer) {
	s.RegisterService(&EmployeeService_ServiceDesc, srv)
}

func _EmployeeService_FetchTopStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).FetchTopStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/FetchTopStories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).FetchTopStories(ctx, req.(*TopCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_FetchItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopCountResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).FetchItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/FetchItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).FetchItems(ctx, req.(*TopCountResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeService_ServiceDesc is the grpc.ServiceDesc for EmployeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTopStories",
			Handler:    _EmployeeService_FetchTopStories_Handler,
		},
		{
			MethodName: "FetchItems",
			Handler:    _EmployeeService_FetchItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/messages.proto",
}
