// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import ()

type LoginInfo struct {
	ID       int32
	Username string
	Password string
}

type UserList struct {
	ID     int32
	UserID int32
	Name   string
}

type UserTask struct {
	ID        int32
	ListID    int32
	Text      string
	Completed bool
}
